### ISSUE TITLE
加入我们[ Join us ].

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#1]
有兴趣一起维护这一项目的，可以在此留言，谢谢支持！

If you like to join us, please let me know, thanks!

**Comment by luzhlon** [comment]
支持！

**Comment by yixingming** [comment]
紧紧抱住大神们大腿

**Comment by monkeydterry** [comment]
申请加入，

会基本vim script..

**Comment by DaSea** [comment]
加一个!

**Comment by wsdjeg** [comment]
@monkeydterry @DaSea 已经邀请你们两个了。

**Comment by jiahut** [comment]
支持。
有空把我的配置整合到这个框架下

[jiahut/dotvim](https://github.com/jiahut/dotvim)

后来因为切换到neovim，又整了一个
[jiahut/.neo.vim](https://github.com/jiahut/.neo.vim)

**Comment by wsdjeg** [comment]
@jiahut 可以，没问题，我看了下你的两个配置，主要是几个插件，这几个插件，大部分我的配置里面都有的。 我在看看哪些没有的 ，我来加加。

**Comment by wsdjeg** [comment]
[加入群【SpaceVim】](https://jq.qq.com/?_wv=1027&k=43DB6SG)

**Comment by wsdjeg** [comment]
@zer4tul Would you like to have a try with current project? we also need help with plugin groups.

**Comment by yqrashawn** [comment]
申请加入, 目前spacemacs用户, 之前用过很长一段时间的vim, 基本的viml比较熟悉, 会lisp

**Comment by wsdjeg** [comment]
@yqrashawn 中文用户可以加入我们群聊聊，开发主要还是在github上面。

**Comment by wsdjeg** [comment]
@lilydjwg 我遇到有一个用户在使用fcitx.vim 有点问题，应该是`echom error` 了。 目前这个项目知道的大多数是国外用户，国内真没好的推广平台，我在V2EX上发了个 帖子，

https://www.v2ex.com/t/332637

**Comment by lilydjwg** [comment]
@wsdjeg 什么问题呢？

**Comment by wsdjeg** [comment]
```
        echohl WarningMsg
        echomsg "socket file of fcitx not found, fcitx.vim not loaded."
        echohl None
        finish
```

应该是这段文字打印了，不过现在联系不上提问题的人，等我在找找吧。

**Comment by wsdjeg** [comment]
@co1inlee 你应该尝试，这一个SpaceVim，这是一个模块化的配置，采用了spacemacs的原理，但是不采用文件结构。

**Comment by colinlabs** [comment]
@wsdjeg 感谢，目前GUI下使用的是spacemacs，但是终端使用的比GUI多，所以想配置一套vim的配置，在服务器和终端下使用，ps. 之前发现了space-vim，现在目前基于这个修改了些配置！！

**Comment by wsdjeg** [comment]
恩，可以关注下这个项目，我的主要工作环境是终端，不怎么用gui.应该和你比较类似。

**Comment by wsdjeg** [comment]
@fno2010 Maybe you can try with this peoject.

**Comment by fno2010** [comment]
@wsdjeg you are doing something really cool. I like its **lazy load** mechanism. But something I'm looking for is still missed in this project. The major missing is a decoupled package management. **Spacemacs** will call it **Layer**. But whatever it is named, a decoupled package management will make the configuration system extensible.

I'm trying [liuchengxu/space-vim](https://github.com/liuchengxu/space-vim) recently. And if you are interested, you can take a look at the design philosophy of this project. I will be always pleased to join your discussion. :)

Btw. the name of this organization is very good. You are an early mover. ;)

**Comment by wsdjeg** [comment]
@fno2010 what is the missing part? I will add it. SpaceVim's goal is different from space-vim, the main goal of SpaceVim is to make vim support deveopping different language and doing different intresting things. It is not just try to make same thing as spacemacs, and what I catch from spacemacs is just the Idea of modular configuration. 

I do not think we should use same file structure as spacemacs. vim is not emacs, the way how vim load scripts is different from emacs, so SpaceVim will not use file structure as spacemacs.

BTW, I hope you can give a try to this project, SpaceVim need more users who use different language.

**Comment by wsdjeg** [comment]
If you find the different between them, you will find why Shougo and mhinz support this project.

**Comment by fno2010** [comment]
@wsdjeg I see you want to do something different. And I totally agree that the modular configuration is very important. Actually I tried this project yesterday, but I didn't find a very clear design about the modular configuration. Or I missed anything crucial? If I'm wrong, please correct me.

If your main goal is to support developing different language, I cannot agree with you. It should be the goal of vim. We want to build an easy-to-use distribution for vim. Simplifying the user config and usage should be the main goal. How about posting a clear design first to get more people support you?

**Comment by wsdjeg** [comment]
I use plugins groups to manager all plugins, the user only need load the groups he want. and SpaceVim will support the plugin for differnt language, such as completion and checker, and I use neomake as default checker, I am ownner of neomake github org.

**Comment by wsdjeg** [comment]
I do not care how SpaceVim looks like ,so I will not use statusline same as space-vim, I think airline is enough.

**Comment by fno2010** [comment]
@wsdjeg **plugins groups** may be a good story. But I cannot find any design document and implemention of it. It is not clear for me. Where can I check anything about it? And how can I try it?

**Comment by wsdjeg** [comment]
need more work about it, should be talked under #9 , now only a simple implemetion `:h g:spacevim_plugin_groups`.

**Comment by fno2010** [comment]
Moved the discussion to #9 :)

**Comment by wsdjeg** [comment]
clossing, will move to readme and website.

**Comment by zer4tul** [comment]
@wsdjeg OK

**Comment by wsdjeg** [comment]
@zer4tul welcome, I will invite you.

**Comment by wsdjeg** [comment]
@zhaoyingjie

可以试试我们的SpaceVim, 默认使用的是neocomplete，neovim下默认是deoplete，都比ycm安装简单，功能强大。

**Comment by Yingjie-Zhao** [comment]
话说你是怎么找到我的...😂 @wsdjeg

**Comment by wsdjeg** [comment]
@zhaoyingjie 我也很关注space-vim的进展，不过我还是希望同时支持下SpaceVim, 貌似space-vim也学了我们的模式，采用autoload。

**Comment by Yingjie-Zhao** [comment]
是的，不过光从文件目录来看的话，space-vim更加浅显一点
            在2017年01月23日 23:46，Wang Shidong 写道： @zhaoyingjie 我也很关注space-vim的进展，不过我还是希望同时支持下SpaceVim, 貌似space-vim也学了我们的模式，采用autoload。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SpaceVim/SpaceVim","title":"SpaceVim/SpaceVim","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SpaceVim/SpaceVim"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wsdjeg in #1: @zhaoyingjie 我也很关注space-vim的进展，不过我还是希望同时支持下SpaceVim, 貌似space-vim也学了我们的模式，采用autoload。"}],"action":{"name":"View Issue","url":"https://github.com/SpaceVim/SpaceVim/issues/1#issuecomment-274523584"}}}

**Comment by wsdjeg** [comment]
@zhaoyingjie 
其实space-vim也是不错的项目，但是，我的这个SpaceVim项目虽然才不到一个月，准确来说，因该是3周不到，但是这原先是我dotfile内的vim配置，打磨了很久很久。当初我也是用的模块化配置。独立出来后，支持的人不少。希望这个项目可以越做越好，我也希望更多的人加入进来，帮助一起维护。

**Comment by Yingjie-Zhao** [comment]
嗯嗯，确实很棒，我也很荣幸能够加入你们，虽然不是很熟，但是还是希望能够尽自己的一份力。
            在2017年01月24日 00:35，Wang Shidong 写道： @zhaoyingjie
其实space-vim也是不错的项目，但是，我的这个SpaceVim项目虽然才不到一个月，准确来说，因该是3周不到，但是这原先是我dotfile内的vim配置，打磨了很久很久。当初我也是用的模块化配置。独立出来后，支持的人不少。希望这个项目可以越做越好，我也希望更多的人加入进来，帮助一起维护。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SpaceVim/SpaceVim","title":"SpaceVim/SpaceVim","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SpaceVim/SpaceVim"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wsdjeg in #1: @zhaoyingjie \r\n其实space-vim也是不错的项目，但是，我的这个SpaceVim项目虽然才不到一个月，准确来说，因该是3周不到，但是这原先是我dotfile内的vim配置，打磨了很久很久。当初我也是用的模块化配置。独立出来后，支持的人不少。希望这个项目可以越做越好，我也希望更多的人加入进来，帮助一起维护。"}],"action":{"name":"View Issue","url":"https://github.com/SpaceVim/SpaceVim/issues/1#issuecomment-274539470"}}}

**Comment by wsdjeg** [comment]
感谢支持。
