### ISSUE TITLE
Use clipboard in file manager

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#1042]
new keybings: `y` for copy file, `p` for paste file

- copy file from vim file manager to system file manage
- copy file from vim file manager to vim file manager
- copy file from system file manager to vim file manager
- ~~copy file from system file manager to system file manager~~

ref: 

https://askubuntu.com/questions/11925/a-command-line-clipboard-copy-and-paste-utility

https://askubuntu.com/questions/210413/what-is-the-command-line-equivalent-of-copying-a-file-to-clipboard

**Comment by wsdjeg** [comment]
@Shougo

I will implement the feature in spacevim. to do this, I need some plugin API from vimfiler.

- get cursor files/dirs path : `vimfiler#get_filename()`
- get marked files/dirs : `join(vimfiler#get_marked_filenames(b:vimfiler), "\n")`

I hope these will not be changed in the feature.

**Comment by wsdjeg** [comment]
@lifecrisis  I also want to implement the custom keybings for nerdtree, so I hope the apis will not be changed in the feature.

- get cursor file/path `g:NERDTreeFileNode.GetSelected().path.str()`

**Comment by Shougo** [comment]
> I hope these will not be changed in the feature.

The features are not changed.  Because, I will create the new file manager instead of breaking the changes.

**Comment by lifecrisis** [comment]
@wsdjeg, if you're talking about that specific function call, it should *not* change.  The NERDTree API is very stable at this point. If you use function calls defined on the major "node" objects (files, directories, bookmarks) you should be fine.

Note that you should **never** use a function that starts with an underscore.  In the NERDTree, these functions are considered private within the prototype in which they are defined.

I may fork the project in the future to continue my work on improving the plugin in a new major version.  Frankly, this needs to happen sooner rather than later.  However, backwards compatibility will always remain a top priority.

**Comment by lifecrisis** [comment]
I'm not completely clear on what you're doing here, @wsdjeg.  Are you copying the path name? The file contents?
