### ISSUE TITLE
.local.vim doesn't work

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#107]
### Expected behavior, english is recommend
I set font and window size in .local.vim both ~ and .spacevim directory 
"VIM(Gvim)编辑中文乱码问题
"
set encoding=UTF-8
set termencoding=UTF-8
set fileencoding=UTF-8
set fileencodings=UTF-8,GB18030,GBK,GB2312,chinese,ucs-bom
set langmenu=en_US
language messages en_US.UTF-8
""窗口大小
set lines=30
set columns=100
"显示字体
"Linux
"set guifont=Monaco\ Bold\ 12
set guifont=YaHei\ Consolas\ Hybrid\ 12

But it doesn't work 
Did i do something wrong ?
![screenshot_2017-01-15_14-28-39](https://cloud.githubusercontent.com/assets/12682385/21960708/f9b0a8d8-db2e-11e6-8241-668105447eec.png)

### Environment Information
- OS:Arch Linux X86_64
- vim version: 8.0.170
- neovim version:

### The reproduce ways from Vim starting (Required!)
the vim in terminal or gvim in panel

**Comment by wsdjeg** [comment]
@SeAL80s `~/.local.vim` is not recommend, you should use `~/.SpaceVim.d/init.vim`. but I can not reprodue this issue, what is the value of guifont? you can get it by `:echo &guifont`. I think it is due to your wrong conifg. 

BTW you can select font in gvim's gui menu, after select the font you want, get the value of guifont by `:echo &guifont`, then add this to custom config file.
