### ISSUE TITLE
Find way to disable tag regenerate operation invoked by tagbar on saving

### ISSUE THREAD

**Issue by yqrashawn** [wsdjeg/SpaceVim#129]
Vim go no responsive when write large file because of this.

**Comment by Shougo** [comment]
Hm.  I think tagbar should generate the tag file asynchronously.

**Comment by wsdjeg** [comment]
Yeah, I have read doc of Ragnar,it do not support async.

**Comment by yqrashawn** [comment]
And I didn't find any good alternative plug. There are ways to generate tag file smart and asynchronously with other tag management plug or even with other program. There must be a plug just read tag file and display tags in a buffer. Maybe it's need user to give the naming rule of tag file and can find tag file from vim's __tag__ setting.

**Comment by Shougo** [comment]
Hm.
neoinclude.vim generates the tag file asynchronously.

**Comment by wsdjeg** [comment]
hi, @majutsushi, I do not recommend people open duplicate issue on github, as some people ask for async featrue support in tagbar, what do you think about it?

**Comment by janlarres** [comment]
The problem is not generating the tags, that is very fast. It's creating the tree structure out of them, which is a bit slow since Tagbar has to do a somewhat complex analysis due to the ctags output not containing all of the information that is necessary to easily create the scope tree. And unfortunately Vim functions can't be run asynchronously.

I'm currently working on a rewrite of that algorithm that should hopefully speed things up. I was also thinking about changing the autocommands a bit so that instead of doing the update directly when writing, it will instead do it on the first `CursorHold` event after writing. That should make it much less noticeable.

**Comment by wsdjeg** [comment]
@majutsushi nice works, I like `Updatting tagbar tree on the first CursorHold event after writing` feature.

**Comment by janlarres** [comment]
I have now implemented the optimizations that I mentioned above, so things should be noticeably faster.

**Comment by wsdjeg** [comment]
@majutsushi Thanks for your works, I just test it, works well for me.  :+1:
