### ISSUE TITLE
[unite.vim] Invalid source name "colorscheme" is detected.

### ISSUE THREAD

**Issue by robjac** [wsdjeg/SpaceVim#1471]
## Expected behavior, english is required
I should be able to choose a color scheme via this menu; but it just fails to ever open/load; unite is no longer being developed; is denite an alternative?

## The reproduce ways from Vim starting (Required!)
<kbd>SPC T s</kbd>

## Debug info 

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
[unite.vim] Invalid source name "colorscheme" is detected.
[unite.vim] unite.vim: Invalid source

**Comment by wsdjeg** [comment]
Sorry, we just disable the unite layer. so the unite-colorscheme can not be called.

in SpaceVim, we have
-  `colorscheme` layer which provides many colorscheme.  
- `unite` layer provides many unite sources
- `denite` layer provide denite and denite-sources

and we make some discussion in #1436 , this discussion is about which layer should be enabled by default. I think colorscheme should be disabled by default, but only the default theme will be loaded.

in current version of spacevim, we can not disable unite.vim, because vimfiler requires unite.vim

**Comment by robjac** [comment]
oh ok; no worries; is there a way to get this working? ; I'm pretty sure this is working for me on my other laptop. or is this still an open discussion / issue? (It seems like that judging by the _ongoing_ discussion)

**Comment by wsdjeg** [comment]
you can load the unite layer by:

```vim
call SpaceVim#layers#load('unite')
```

**Comment by robjac** [comment]
That doesn't seem to work when I add `call SpaceVim#layers#load('unite')` to `~/.SpaceVim.d/init.vim`

**Comment by wsdjeg** [comment]
@robjac This key binding `SPC T s` is moved to fuzzy finder layers ( #1502 ), and choose one of these fuzzy layers, `SPC T s` should works. BTW, colorscheme is not loaded by default, so if you want to fuzzy find other awesome colorscheme, you need to load colorscheme layer.

**Comment by robjac** [comment]
Yep! Thanks for the info! Aftrer a few SPUpdates it seems to have fixed it self...

Thanks
