### ISSUE TITLE
Getting started tutorial

### ISSUE THREAD

**Issue by ijsnow** [wsdjeg/SpaceVim#1829]
Hello! Just tried this out and it looks awesome. I was thinking of switching over to SpaceVim from a custom setup because I'm getting too lazy to keep up with my setup. It looks really nice and seems like a lot of thought has gone in to keeping it fast while adding a lot of very useful features and making it extensible. Nice work!

I just uninstalled it to go back to my setup because I didn't want to lose too much productivity while making the switch and learning everything. I spent some time looking through the docs and couldn't figure out how to do basic things. Just a few of the things that were unclear:

- What is `<leader>`? I saw that it said `s` but I couldn't get any of the commands with `<leader>` in it to work
- What is `SPC`? I couldn't figure out what it was. Seemed like an alternate `<leader>` but not sure.
- Where to put `call` commands? I tried setting up the typescript layer but have no idea where to put it. I tried putting it in `~/.SpaceVim.d/init.toml` and that obviously didn't work but for the life of me I couldn't figure out where to actually put a custom config file and even what filetype/syntax its supposed to be. Is it just a `.vim` file?

Could you consider creating a tutorial that just goes over the basics enough to get someone at least to the point where they can mess around with it? Doesn't need to be a 0-100 tutorial, just a 0-50.  Similar to  [`vim-go`'s awesome tutorial](https://github.com/fatih/vim-go-tutorial) but maybe doesn't even need to have that much content. Somewhere between the "quick start" guide you already have and the docs.

**Comment by wsdjeg** [comment]
1. the leader key is `` \ `` by default. 

2. SPC means Space on the keyboard

3. you can use bootstrap function for vim script

there is a Chinese version spacevim tutorial https://everettjf.gitbooks.io/spacevimtutorial/content/

maybe we should also provide a English version.

**Comment by rcrx** [comment]
> maybe we should also provide a English version.

Affirmative.

**Comment by ijsnow** [comment]
1. So is this just talking about on windows? That's what I thought but I didn't see anything else defining the leader in the docs.

<img width="665" alt="screen shot 2018-06-12 at 7 58 32 pm" src="https://user-images.githubusercontent.com/11557758/41495536-1d62e0fa-70ef-11e8-9908-70e2e33db4c0.png">

2. SPC is space.... duuuuh 🙈 

An English version would be nice! I'd help translate if I could!

**Comment by wsdjeg** [comment]
@ijsnow  thanks

@everettjf hello, what do you think about this?

**Comment by everettjf** [comment]
@wsdjeg Of course, I have already receive some emails asking for English version. Thanks for all your approbate and encouragement.  Since I do not have so much time writing/updating it this month and frankly speaking the Chinese version needs update, could you give some advice on them(both English and Chinese version). I will plan for it next month (2018-07). 😃 

--

Update 2018-08: Sorry for that while I am changing my job~

**Comment by wsdjeg** [comment]
gitbook is too slow for me, would you like to use github page? SpaceVim also need an offical tutorial. It should different from the documentation and focuse on usage.

**Comment by matt1003** [comment]
I have been wanting to switch to SpaceVim for some time now, but the road block is porting across my existing functionality. As an avid user of Vim, I have built up quite the extensive vimrc; which is now too much to maintain. The problem is that I cannot give it up cold-turkey, as it contains a lot of functionality that I use from day to day.

What would be great is some sort of "migration" guide. I have already spend several hours reading the SpaceVim documentation, and googling around, but I am still scratching my head. Ideally I just want to point my SpaceVim at my vimrc, and then rip out the functionality I no longer need. I have read about bootstrap functions, but I don't quite understand how to use these in this situation.

I am not here just to complain; instead I am keen to help out and contribute. I think SpaceVim is a great idea, not just for vim newbies, but also for those experienced users who are sick of managing ever-growing vimrcs.

**Comment by wsdjeg** [comment]
I have read @everettjf's tutorial many times, and I think it is a better idea for users. I want to add tutorial on spacevim website.  included english version and chinese version.

the maybe the urls are:

- `spacevim.org/use-vim-as-ide/` for geneal IDE-like feature.
- `spacevim.org/use-vim-as-java-ide/` for java language specific feature.
- `spacevim.org/use-vim-as-python-ide/` for python language specific feature.
- etc

and the chinese version urls are:

- `spacevim.org/cn/use-vim-as-ide/` for geneal IDE-like feature.
- `spacevim.org/cn/use-vim-as-java-ide/` for java language specific feature.
- `spacevim.org/cn/use-vim-as-python-ide/` for python language specific feature.
- etc
