### ISSUE TITLE
An Exception process has  issue

### ISSUE THREAD

**Issue by blankxyz** [wsdjeg/SpaceVim#1909]
## Expected behavior, english is required
1.  Using brew install macvim
2.  Using "curl -sLf https://spacevim.org/cn/install.sh | bash" install SpaceVim

## The reproduce ways from Vim starting (Required!)
<kbd>
Error detected while processing /Users/baibing/.SpaceVim/config/general.vim:

line   23:

E185: Cannot find color scheme 'desert'

Error detected while processing function SpaceVim#end[82]..zvim#util#source_rc:

line    2:

E171: Missing :endif

Error detected while processing /Users/baibing/.SpaceVim/vimrc:

line   11:

E171: Missing :endif

Press ENTER or type command to continue
</kbd>
## Debug info

This bug is raise from line /.SpaceVim/config/general.vim

    try
        exec 'set background=' . g:spacevim_colorscheme_bg
        exec 'colorscheme ' . g:spacevim_colorscheme
    catch
        exec 'colorscheme '. g:spacevim_colorscheme_default
    endtry

The reason of "Cannot find color scheme 'desert'" is /Application/MacVim.app not exsit。
After maked link of macVim， it's run.

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

**Comment by wsdjeg** [comment]
sorry, nothing can be done in SpaceVim, desert is a built-in colorscheme in vim.

**Comment by JamesMcMahon** [comment]
Sorry what is the solution to this? I just did a fresh install on macOS 10.14 and got the exact same issues.

Is the problem with the brew install version of vim?

---
EDIT: Oddly this seemed to fix itself when I opened nvim and it updated itself. Very odd because it was not my first time opening nvim post install, it only happened when I switch my git message editor to nvim. No idea what happened there. Now I get:

```
Error detected while processing function SpaceVim#end:
line  102:
E484: Can't open file /usr/local/share/vim/syntax/syntax.vim
Press ENTER or type command to continue
```

May be do to me not using `/usr/local/` as my brew prefix, I use a directory in my ~ instead.

---

Fixed that with a symlink and now I get:

```
Error detected while processing /Users/jamie/.brew/Cellar/vim/8.1.0600_2/share/vim/vim81/syntax/syncolor.vim:
line   36:
E254: Cannot allocate color Orange
E254: Cannot allocate color Orange
Press ENTER or type command to continue
```

Not sure what is going on but it may be specific to my setup. nvim works just fine.
