### ISSUE TITLE
Timers in FlyGrep throws error when used with vim-matchup

### ISSUE THREAD

**Issue by kristijanhusak** [wsdjeg/SpaceVim#2160]
I'm using [vim-matchup](https://github.com/andymass/vim-matchup) plugin, and i'ts option to deffer highlights, which uses timers in the background. Flygrep has a call to stop the timer, and default timer id is 0. In Neovim, timers start from 0, where in Vim it starts from 1. Here's the issue i reported there, you have a brief explanation what causes the error, and also a screenshot 

https://github.com/andymass/vim-matchup/issues/39

**Comment by wsdjeg** [comment]
I will try to test it. ~~the timer feature is added in neovim first, and I can not understand why vim team like to add uncomaptible api, same as job's api. I am watching neovim's repo, the neovim develop team never merge uncompatible patch.~~

just report to neovim team, and maybe it will be fixed in neovim.

**Comment by kristijanhusak** [comment]
Yeah i think it was added by Neovim first, so Vim should be compatible with it.

**Comment by wsdjeg** [comment]
but I think the timer id should start with 1, which is same as job id.

**Comment by bfredl** [comment]
No, vim got vimL timers first, I ported them to nvim, but made a mistake apparently :P

**Comment by wsdjeg** [comment]
@bfredl sorry for my wrong words.

**Comment by wsdjeg** [comment]
@kristijanhusak I just fix it in flygrep, it should works well with current version of neovim.
