### ISSUE TITLE
timeoutlen config dont work

### ISSUE THREAD

**Issue by SionLv** [wsdjeg/SpaceVim#2322]
I configured the timeoutlen parameter in init.toml, but it didn't work. Where should I configure it correctly

**Comment by zonghi** [comment]
![image](https://user-images.githubusercontent.com/44047171/49627108-ea7c3300-fa17-11e8-97eb-cf329ada96d4.png)

**Comment by wsdjeg** [comment]
Ok, maybe we should add an option for setting this. before this feature is added, you can use bootstrap funtion and add `set timeoutlen=1000` into the bootstrap function.

**Comment by yinflying** [comment]
Maybe We should create a template `myspacevim_before.vim` and `myspacevim_after.vim` at `~/.Spacevim.d/`.

**Comment by wsdjeg** [comment]
@yinflying no, we should not generate too many files in users home dir.

**Comment by wsdjeg** [comment]
please use bootstrap function to set this option, as in SpaceVim, we do not use this options, so I do not add new spacevim option for it.

**Comment by ghost** [comment]
Perhaps there is an error with your documentation then, because the SpaceVim documentation page says `By default the guide buffer will be displayed 1000ms after the keys being pressed. You can change the delay by setting 'timeoutlen' option to your liking (the value is in milliseconds).`

Is that incorrect?

**Comment by wsdjeg** [comment]
it is correct. it means set Vim option. you can use :set timeoutlen=1000

---

wsdjeg

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] timeoutlen config dont work (#2322)
发件人：Christopher
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,State change


Perhaps there is an error with your documentation then, because the SpaceVim documentation page says By default the guide buffer will be displayed 1000ms after the keys being pressed. You can change the delay by setting 'timeoutlen' option to your liking (the value is in milliseconds).

Is that incorrect?

―

**Comment by ghost** [comment]
That works. I would suggest updating the documentation to make it clear that this is not a SpaceVim option, but a regular vim option, I think that would prevent a lot of confusion

**Comment by wsdjeg** [comment]
Ok done, I have updated the doc.

________________________________
wsdjeg@outlook.com
