### ISSUE TITLE
Feature Request: Pinpoint exact error in bootstrap_before(after) function

### ISSUE THREAD

**Issue by kabasakalis** [wsdjeg/SpaceVim#2329]
If I have an error in `bootstrap_before` function, `SPDebugInfo` will show me `failed to call bootstrap_before action` which is extremely vague and tells me nothing about the error. Forces me to restart spacevim every time I change something just to be sure that I know what I did wrong. Otherwise there's  no way to tell what went wrong.
Also, is there a way to split `bootstrap_before` in several different files ?

**Comment by wsdjeg** [comment]
I have implemented this feature, please update SpaceVim.

发自我的华为手机

-------- 原始邮件 --------
主题：[SpaceVim/SpaceVim] Feature Request: Pinpoint exact error in bootstrap_before(after) function (#2329)
发件人：Spiros Kabasakalis
收件人：SpaceVim/SpaceVim
抄送：Subscribed


If I have an error in bootstrap_before function, SPDebugInfo will show me failed to call bootrasp_before action which is extremely vague and tells me nothing about the error. Forces me to restart spacevim every time I change something just to be sure that I know what I did wrong. Otherwise theres' no way to tell what went wrong.

―

**Comment by kabasakalis** [comment]
Just tried it, exception type and line number, awesome!  Thank you for immediate response and implementation!

**Comment by wsdjeg** [comment]
welcome, but in current version, only support bootstrap_before, if error happened in bootstrap_after, it will not be logged. I will add this feature too.

________________________________
wsdjeg@outlook.com
