### ISSUE TITLE
Following quick start guide has errors

### ISSUE THREAD

**Issue by chrisamow** [wsdjeg/SpaceVim#2346]
docker pull was successful without problems, but then
```
➜  ~ ★ docker run -it --rm spacevim/spacevim nvim
[dein] Error occurred while executing hook: deoplete.nvim
[dein] Vim(call):E121: Undefined variable: g:_spacevim_autocomplete_delay
Press ENTER or type command to continue
```
running on linux mint 19 cinnamon

## Expected behavior, english is required
vim to start without errors

## Debug info
never makes it this far

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by mr-ubik** [comment]
I have the same issues as well. Fresh SpaceVim installation on an Arch system. When continuing it throws the following error each time I switch between Normal and Insert mode.

`[dein] Vim(call):E121: Undefined variable: g:_spacevim_autocomplete_delay ` 

#2362 Covers this error but I believe them to be related.

**Comment by y9c** [comment]
I have the same issue.  Seem that there is some error in python layer. 

This errors happens when python file trigger the auto complete function.

---

`_spacevim_autocomplete_delay` in autocomplete layer is not work properly. 
Adding `let g:_spacevim_autocomplete_delay = 10` in the configure file will suppress the error.

**Comment by wsdjeg** [comment]
Fixed, please updated spacevim, sorry for later reply.
