### ISSUE TITLE
Error installing spacevim on Windows

### ISSUE THREAD

**Issue by xnng** [wsdjeg/SpaceVim#2381]
## Expected behavior, english is required

No vimproc_cygwin.dll was found

## The reproduce ways from Vim starting (Required!)

![snipaste_2018-12-26_13-31-15](https://user-images.githubusercontent.com/38936252/50435340-d8f1c100-091b-11e9-9765-667779e4b515.png)

First, I tried to install it in GVIM and the script was working properly, but there was an error. When I tried to enlarge the window, the error disappeared, so I couldn't see the complete error message.

So I deleted GVIM and the files I just downloaded when I installed it.

I used the Linux script, but I noticed that there was a function in the script to install fonts, but windows fonts were not installed that way. I think that font should be used to solve the problem of Unicode character display abnormality, so I deleted the function to install fonts, and manually installed the fonts.

Then I run the script in Git bash, and everything worked.

![snipaste_2018-12-26_14-04-05](https://user-images.githubusercontent.com/38936252/50435554-ba3ffa00-091c-11e9-8097-cbeecb2fc2d3.png)

But when I opened vim, I found that a plug-in installation failed.

![snipaste_2018-12-26_14-08-54](https://user-images.githubusercontent.com/38936252/50435596-e0659a00-091c-11e9-88de-ba79433ecb3b.png)

When I opened VIM again, I saw a complete error message, which I thought was consistent with the previous error message when installing it in gvim.

![snipaste_2018-12-26_14-09-23](https://user-images.githubusercontent.com/38936252/50435630-09862a80-091d-11e9-8881-78159904c84a.png)

That error is one less file called vimproc_cygwin.dll

I went to the repo and looked, but I couldn't find it.

![snipaste_2018-12-26_14-26-57](https://user-images.githubusercontent.com/38936252/50435704-5ff36900-091d-11e9-8cfc-53e6960b87aa.png)

The original repo seems to have feedback on similar problems, but it does not seem to have been repaired.

I want to ask, do I really need this file?

**Comment by wsdjeg** [comment]
You can download the dll file from vimproc release page. and copy them to lib dir.


---

Shidong Wang

-------- 原始邮件 --------
主题：[SpaceVim/SpaceVim] Error installing spacevim on Windows (#2381)
发件人：xnng
收件人：SpaceVim/SpaceVim
抄送：Subscribed

Expected behavior, english is required

No vimproc_cygwin.dll was found

The reproduce ways from Vim starting (Required!)

[snipaste_2018-12-26_13-31-15]<https://user-images.githubusercontent.com/38936252/50435340-d8f1c100-091b-11e9-9765-667779e4b515.png>

First, I tried to install it in GVIM and the script was working properly, but there was an error. When I tried to enlarge the window, the error disappeared, so I couldn't see the complete error message.

So I deleted GVIM and the files I just downloaded when I installed it.

I used the Linux script, but I noticed that there was a function in the script to install fonts, but windows fonts were not installed that way. I think that font should be used to solve the problem of Unicode character display abnormality, so I deleted the function to install fonts, and manually installed the fonts.

Then I run the script in Git bash, and everything worked.

[snipaste_2018-12-26_14-04-05]<https://user-images.githubusercontent.com/38936252/50435554-ba3ffa00-091c-11e9-8097-cbeecb2fc2d3.png>

But when I opened vim, I found that a plug-in installation failed.

[snipaste_2018-12-26_14-08-54]<https://user-images.githubusercontent.com/38936252/50435596-e0659a00-091c-11e9-88de-ba79433ecb3b.png>

When I opened VIM again, I saw a complete error message, which I thought was consistent with the previous error message when installing it in gvim.

[snipaste_2018-12-26_14-09-23]<https://user-images.githubusercontent.com/38936252/50435630-09862a80-091d-11e9-8881-78159904c84a.png>

That error is one less file called vimproc_cygwin.dll

I went to the repo and looked, but I couldn't find it.

[snipaste_2018-12-26_14-26-57]<https://user-images.githubusercontent.com/38936252/50435704-5ff36900-091d-11e9-8cfc-53e6960b87aa.png>

The original repo seems to have feedback on similar problems, but it does not seem to have been repaired.

I want to ask, do I really need this file?

―

**Comment by xnng** [comment]
I downloaded the file and renamed it to vimproc_cygwin.dll，The error disappeared.

Although I only know if it really solves the problem, I will continue to explore it. Thank you.
