### ISSUE TITLE
How do I backup my bookmarks file?

### ISSUE THREAD

**Issue by jhessin** [wsdjeg/SpaceVim#2911]
I have been using bookmarks quite extensively. I use several different machines and I have my project files shared through git. I'm going on a trip and won't have my primary development computer and I would like to port my bookmarks over to my laptop.

I seem to remember the bookmarks being stored in a particular file before, but I can't remember where that file is.

**Comment by wsdjeg** [comment]
please do not use github issue for asking question. issue is for bug report and feature request. MUST follow the issue temple.

---

wsdjeg

-------- 原始邮件 --------
主题：[SpaceVim/SpaceVim] How do I backup my bookmarks file? (#2911)
发件人：Jim Hessin
收件人：SpaceVim/SpaceVim
抄送：Subscribed

Expected behavior, english is required
The reproduce ways from Vim starting (Required!)
Debug info

Please press SPC h I, debug info will be put into clipboard, then paste all content below.

Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

―

**Comment by jhessin** [comment]
Sorry - couldn't find any better place to ask. Google searching came up with nothing. Just found your gitter room - I'll try there.
