### ISSUE TITLE
Could support Deep TabNine？

### ISSUE THREAD

**Issue by leafonsword** [wsdjeg/SpaceVim#2964]
Deep TabNine is a auto-complete plugin using machine learning, seems stringer than others, could SpaceVim support Deep TabNine?

**Comment by wsdjeg** [comment]
just find a plugin, you can use custom_plugin option to add it.

https://github.com/tbodt/deoplete-tabnine

if we add this plugin into spacevim, which layer do you think it should be added?

**Comment by xiaoniu-578fa6bff964d005** [comment]
I just add tabnine-vim support with monkey patch. [repo](https://github.com/xiaoniu-578fa6bff964d005/SpaceVim)
Basically, tabnine would be another choice in autocomplete layer.
In order to use, just change `let g:spacevim_enable_ycm = 1` into `let g:spacevim_enable_tabnine = 1`.
Documents and details still need polish.

**Comment by dariye** [comment]
Having tabnine would be awesome @wsdjeg

**Comment by wsdjeg** [comment]
@xiaoniu-578fa6bff964d005 tabline is not a complete method, both ycm and deoplete can support tabline, maybe we can add a layer option for tabline, if it is enabled, load the plugin based on th ecompletion methond.

**Comment by wsdjeg** [comment]
hmm, I do not use tabline, but PR is welcome. I recommen to use layer option to enable/disable tabline support.
