### ISSUE TITLE
Multiline REPL support for Perl

### ISSUE THREAD

**Issue by weisheng-binary** [wsdjeg/SpaceVim#3219]
Is is possible to have multiline REPL support for PERL? Something similar to this https://metacpan.org/pod/Devel::REPL::Plugin::MultiLine::PPI

**Comment by jyscao** [comment]
does this plugin help with what you want in any way?

https://github.com/sillybun/vim-repl

**Comment by wsdjeg** [comment]
this has been done in spacevim. the key binding is `SPC l s s` in visual line mode.

**Comment by weisheng-binary** [comment]
> this has been done in spacevim. the key binding is `SPC l s s` in visual line mode.

It doesn't work. For example,

```
sub example{
...
};
```

will be thrown in as 

```
>>> sub example{
>>> ...
>>> };
```

instead of 

```
>>>sub example{
...
};
```

There is no support of multiline for perli.

**Comment by wsdjeg** [comment]
@weisheng-binary This should be a feature request of perli instead of SpaceVim, the spacevim repl plugin is a vim plugin wihch will run a command line tool, and communicate with via stdin/stdout.

BTW, instead of request new feature in perli, you can create your own perl repl script, such as 

```perl
use Devel::REPL;

my $repl = Devel::REPL->new;
$repl->load_plugin('LexEnv');
$repl->load_plugin('History');
$repl->load_plugin('MultiLine::PPI');
$repl->run;
```

and put in into `~/bin/perlrepl.pl`.

then use bootstrap function to change the repl command of perl layer to `perl ~/bin/perlrepl.pl`.
