### ISSUE TITLE
Todo manager open buffer in Tagbar

### ISSUE THREAD

**Issue by Rom1deTroyes** [wsdjeg/SpaceVim#3239]
When I open a TODO anotation from Todo Manager, the buffer is opened in the Tagbar

## Expected behavior, english is required
TODO anotation choosen in Todo Manager to be opened with the otehr buffers window

## The reproduce ways from Vim starting (Required!)
- Open a project with @TODO anotations
- Open Tagbar (<kbd>F2</kbd>)
- Open Todo Manager (<kbd>SPC a o</kbd>)
- Choose an anotation in the list
- See the buffer opened in the Tagbar window

## Debug info
As I'm on a remote session, it's complicated, I will include more clues if bug is not reproductible :-(
My configuration :
- System : Centos / Kernel : 3.10.0-957.5.1.el7.x86_64
-  vim 7.4
- SpaceVim installed and :SPUpdate from Git repo

## Screenshots
Idem, I will make a screencast if not reproductible

**Comment by jyscao** [comment]
@Rom1deTroyes I'm able to reproduce this bug. And although I don't know how to fix it yet, I've sort of got an idea of what might be causing this issue.

It appears to have to do with the way your window splits are arranged. The Tagbar opens up as the left split by default, thus it will be labeled as the 1st window in your tab. So when you try to open up a buffer from the Todo manager, it will go to that first window split. This problem also occurs with a file manager buffer. Normally the file manager split opens up as a right split, thus becomes window no. 2; but if you swap it over to the left side, so that it's window no. 1, then opening a buffer from the Todo Manager list will also send it to that narrow split previously displaying your files.

Lastly, it also seems to matter what buffer type these windows are displaying, because this problem does not occur when opening buffers that are listed in a quickfix buffer.

**Comment by wsdjeg** [comment]
Ok, let see how denite or ctrlp works,

1. open tagbar
2. open denite or ctrlp
3. selete a file and open
