### ISSUE TITLE
projectmanager should prefer the longest root instead of shortest

### ISSUE THREAD

**Issue by dyno** [wsdjeg/SpaceVim#3332]
https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/plugins/projectmanager.vim#L199

init.toml
```
project_rooter_patterns        = ["Pipfile", ".git/"]
```

for a setup like mine 
```
project/.git
project/whatever/Pipfile
project/whatever/x.py
```
the root should be project/whatever instead of project.

**Comment by wsdjeg** [comment]
no, SpaceVim will use top path as the project root, you need to remove `.git/`.

**Comment by dyno** [comment]
in our setup there are global root projects all are java which should be considered as one "big" project and there are python subproject which are more autonomous/isolate and should be considered a single project. when work in python project i want the project root to be more restricted.  

it's also more natural to think the closest parent that has the root mark directory as the enclosing project. 
and i am pretty sure earlier SpaceVim behave like that, now it changed its behavior.

**Comment by wsdjeg** [comment]
yeah, This has been changed since https://github.com/SpaceVim/SpaceVim/issues/3031#issuecomment-580700111

**Comment by strazto** [comment]
For the case of R, I believe lang#r 's `project_rooter_patterns` is given by:

```r
call add(g:spacevim_project_rooter_patterns, '.Rprofile')
```

This is nearly guaranteed to produce undesired behaviour, since `.Rprofile` is an env setup file that can, and often is defined at the global user level, as well as at a project local level. 

Use of `~/.Rprofile` to setup certain environment variables / store secrets is considered idiomatic and good practice, as exemplified by [this section on its usage R's leading package manager](https://rstudio.github.io/renv/reference/config.html), but use of `~/.Rprofile` will likely break practically every `project_rooter_patterns`.

**Comment by strazto** [comment]
It probably deserves its own issue, but I do think that perhaps `.Rprofile` is not the most optimal pattern to use for lang#r - I'd suggest something in-line with Rstudio's project config format, "package.name.Rproj"

**Comment by 812lcl** [comment]
It would be better if we can make it configurable by language level. At least we can set it in init.toml.
longest or top

**Comment by linusjf** [comment]
This is something I just discovered.

Check whether it's of relevance:

https://cran.r-project.org/web/packages/startup/vignettes/startup-intro.html

**Comment by linusjf** [comment]
https://cran.r-project.org/package=rprojroot


Another package that I found is quite useful to discover the project root.

**Comment by strazto** [comment]
Since we're talking about it, the popular `here` package for R also fuflils the requirement of discovering the project root

That said, I don't think the project rooter plug-in actually tends to call external programs, etc, so both these packages just give an overview of conventional R project / environment structures.

**Comment by linusjf** [comment]
The rprojroot package has in-built criteria that specifies the project root. 

It also allows for flexibility by specifying what file should be found in the project root directory.

For an example of my usage:

https://github.com/Fernal73/LearnR/blob/development/Stats462/Lesson08/birthsmokers.R

I will look at the here package as well.
Thanks for the tip.

**Comment by wsdjeg** [comment]
Thanks, I will checkout this project.

**Comment by wsdjeg** [comment]
the logic of finding the project root is simple, and I do not want to use extra lib. just vim script is ok. and we also provide project root partten to config the flag file.

**Comment by linusjf** [comment]
Wrt the original post, should the project root be prioritised by order of the patterns, or do we need a facility to specify weights for each pattern?

**Comment by wsdjeg** [comment]
This option `project_rooter_patterns` should be improved.

1. add weights for each patterns
2. add document for this option in [website](https://spacevim.org/documentation/#managing-projects)

**Comment by wsdjeg** [comment]
please checkout https://github.com/SpaceVim/SpaceVim/pull/3609
