### ISSUE TITLE
<ESC> not being passed to shell

### ISSUE THREAD

**Issue by wilrnh** [wsdjeg/SpaceVim#3468]
## Expected behavior, english is required

When I press <ESC> in the shell terminal, it should be passed on to the terminal.

Instead, Spacevim captures <ESC> to escape me from the shell terminal.

This is mostly an issue for me because my git commit editor is set to use vim. So if I run a git command that pops open the editor, I cannot <ESC> effectively to complete the git operation.

Notes:
A simple way to "escape" the <ESC> keypress would be sufficient.

Also, simply unmapping <ESC> from the shell layer, would be sufficient. I'm aok with using the `deol` default of `CTRL-\ CTRL-N`

## The reproduce ways from Vim starting (Required!)

1. open shell terminal with `SPC '`
2. run a program that uses <ESC>. I used vim, then switched to INSERT mode with `I`
3. try to pass <ESC> to the program. In vim, I tried to return to NORMAL mode with `<ESC>`
 
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
@wilrnh This is hard to fix, becasue vim use `<Esc>` to switch to normal mode by default, so it will be easier to use `<Esc>` to switch from terminal mode to normal mode.  Instead of using `<Esc>` you can use `jk` to switch from insert mode to normal mode. BTW, why do not have a try with `git` layer, use `SPC g c` to open commit buffer, write it, then use `:wq` to save commit message and commit.

we have discussed before in https://github.com/SpaceVim/SpaceVim/pull/3170

**Comment by wilrnh** [comment]
Thanks for the update @wsdjeg, and keep up the great work! This is pretty much the only blocker keeping me from using the builtin terminal and I hope we can figure out how to resolve this.

Closing this until then.
