### ISSUE TITLE
XDG specification support

### ISSUE THREAD

**Issue by wchmb** [wsdjeg/SpaceVim#3517]
Please add support for XDG base directory specification:\
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

I use to have all my configurations in `XDG_CONFIG_HOME` in order to make backups much simpler.\
In addition, having a clean `$HOME` is always a good idea.

It'd be nice if not only `~/.SpaceVim.d/` but also `~/.Spacevim/` were in `XDG_CONFIG_HOME`.\
Symlinks are not a smart solution for me. So I think the installer/updater script should move the locations.

Many world-renowned applications with a long history in Linx world address the problem overriding the default location using the environment variables (if set).

**Comment by jooize** [comment]
I've noticed a rising tendency of projects to implement the specification, even some that previously have stubbornly refused. I was cautiously skeptical at first because of https://xkcd.com/927/, but have since realized I want everything to support [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

Amusing reading: https://hauleth.dev/post/stop-spreading-crap-at-my-home/

Let's patiently describe thoroughly why this is such a good idea if it meets resistance. :)

**Comment by wchmb** [comment]
Thank you for your comment @jooize, I found your reading suggestions very interesting. 

I'm on the side of **Rob Pyke** (I also recommend [his old post](https://web.archive.org/web/20180827160401/plus.google.com/+RobPikeTheHuman/posts/R58WgWwN9jp)). For me the point is not whether XDG it's a good idea, it's that the original idea of dot files was a very bad decision

**Comment by MarcinWieczorek** [comment]
+1 for this change, is there any progress?

**Comment by wsdjeg** [comment]
@jooize Thanks for you info about XDG base Directory, we can implement this feature. The issue is:

1. vim do not support XDG base directory, you still need to create symlinks from `~/.vim` to `SpaceVim main repo`.

2. how to make compatible with old version of spacevim?

if there is no `~/.SpaceVim.d`, check the `XDG_CONFIC_HOME/.SpaceVim.d`?

**Comment by MarcinWieczorek** [comment]
> if there is no `~/.SpaceVim.d`, check the `XDG_CONFIC_HOME/.SpaceVim.d`?

Usually it's the other way around, the XDG is the default to check. Correct me if I'm wrong.

**Comment by fentas** [comment]
Just as ref from 
- vim itself: https://github.com/vim/vim/issues/2034
- and nvim: https://github.com/neovim/neovim/issues/78 (which has it implemented)

There have been a lot of issues already addressed and some solved.
Would love to see this implemented.

**Comment by wsdjeg** [comment]
Move to https://groups.google.com/d/msgid/spacevim/ME3P282MB1842752371C13639547238C7D4209%40ME3P282MB1842.AUSP282.PROD.OUTLOOK.COM

**Comment by wsdjeg** [comment]
closed, because Vim do not support xdg directory now.

**Comment by oliv3r** [comment]
Vim doesn't support it nativily yet, but is VERY easy to convince vim to play at least nicely.

There's a nice blog post [0] with lots of details, but in short, if you have (well that's what I did) `~/.local/bin/vim` (and a gvim symlink) with just `exec /usr/bin/$(basename "${0}")" -u "${XDG_CONFIG_HOME:-${HOME}/.config}/vim/vimrc" -U -u "${XDG_CONFIG_HOME:-${HOME}/.config}/vim/gvimrc" "${@}"` + the variables in your vimrc, you have a vim compliant with XDG.

[0]: https://blog.joren.ga/vim-xdg
