### ISSUE TITLE
Please delete this shit

### ISSUE THREAD

**Issue by tothlac** [wsdjeg/SpaceVim#3684]
I don't know what the hell is this, but it renamed my .vimrc file, my .vim folder, and it looks like the only thing this thing does is to install its own plugins and moves my plugins to other folders. I'm quite sure it's doing some tricks in the background (hopefully it does not do anything with vim and nvim executables, because that would be a virus not a program). Actually right after I saw spacevim running I immediately wanted to delete the shit, and it took two days to reinstall all plugins because it caused some tricky problems. Delete this repository or modify it's code! It's very bad that you hack .vimrc files the .vim folder and probably the vim executables.

**Comment by wsdjeg** [comment]
you should read the doc carefully! This is the default logic of vim. Vim only load the rc file from .Vim or vimrc. So to init SpaceVim. we need to rename them. But we do not delete them. you just need to rename them back. it will tack only one second! And stop using word like **shit**, otherwise you will be blocked. you can check other vimrc install script or even spacemacs. both of them need to rename origin configuration file!
