### ISSUE TITLE
SpaceVim won't work after updating Lua

### ISSUE THREAD

**Issue by teynav** [wsdjeg/SpaceVim#3691]
![image](https://user-images.githubusercontent.com/40721108/89701431-9cd66d00-d954-11ea-949f-d26b8db62f8c.png)
I am on v1.5.0

**Comment by Shougo** [comment]
You need to rebuild Vim.

**Comment by Compile-Time** [comment]
I have the same issue using Lua 5.4
I created a symbolic link with the name lualib5.3.so that points to lualib5.4.so.

After triggering the helper window I get this error:
![image](https://user-images.githubusercontent.com/18414241/90536892-f290ed80-e17c-11ea-8ff3-d2b2a9ee5c5c.png)

Looking in the [lua change log](https://www.lua.org/manual/5.4/readme.html) for version 5.4 I found this line.
> userdata can have multiple user values

However, the lua manual mentions that macros exist for the old names.
https://www.lua.org/manual/5.4/manual.html#8.3
>  Full userdata now has an arbitrary number of associated user values. Therefore, the functions lua_newuserdata, lua_setuservalue, and lua_getuservalue were replaced by lua_newuserdatauv, lua_setiuservalue, and lua_getiuservalue, which have an extra argument.

> For compatibility, the old names still work as macros assuming one single user value. Note, however, that userdata with zero user values are more efficient memory-wise.

So, in theory the helper window should still work without a problem. But for some reason this is not the case.

**Comment by wsdjeg** [comment]
@Shougo thanks to replay, instead of rebuild vim, as I know, vim provide an option `luadll` which can be set to the path of lua lib. Can we detect the path of lua lib in command line.

**Comment by Shougo** [comment]
> Can we detect the path of lua lib in command line.

it depends on system configuration...
