### ISSUE TITLE
Disable syntax checker or close its window

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#399]
## Expected behavior

Sometimes I won't pay attention to the warnings given by syntax checker.

But I don't know to close it correctly, which is quite annoying.

I want to know how to close it or just disable it **one time** or disable it whenever I want

## Environment Information
- OS: Arch Linux
- vim version: 8.0

## The reproduce ways from Vim starting (Required!)

![image](https://cloud.githubusercontent.com/assets/12933851/24709614/0ba91e64-1a4d-11e7-9887-17868e27a4da.png)

I hate to see this

**Comment by wsdjeg** [comment]
`let g:spacevim_lint_on_save = 0`

**Comment by Gabirel** [comment]
Can I accomplish this goal by any shortcuts? Sometimes, I want it to check for me.

**Comment by wsdjeg** [comment]
hmm, I will add a keymapping.

**Comment by wsdjeg** [comment]
I juet add a mapping `\ck`, and a new feature, lint on the fly. you can enable it via
```viml
let g:spacevim_lint_on_the_fly = 1
```

**Comment by Gabirel** [comment]
You should add this mapping into your document.

**Comment by wsdjeg** [comment]
yeah.

**Comment by Gabirel** [comment]
I can't close the window with `\ck`.

It did close. But pop up again and again.

**Comment by shiftre** [comment]
Are there any other checkers? I'm writing in Python3 and the ``async`` keyword isn't recognized by lint/flake8, it doesn't seem that ``let g:spacevim_lint_on_save = 0`` works either as I still get this windows, (i'm using vim 8.0)

**Comment by Guangyi-Z** [comment]
Hi, neither `\ck` or `let g:spacevim_lint_on_save = 0` works on my Macbook.
I am using a linter of Python. (ref: https://spacevim.org/layers/lang/python/)

I really hate to be distracted from the dim warnings below the current line of code. How can I turn it off? For now I have to stop the whole Python layer to continue my coding.
![image](https://user-images.githubusercontent.com/5117352/43085560-ef60dfd6-8ea3-11e8-8c73-0179a00d3b46.png)

Looking for your help. Thanks.

**Comment by wsdjeg** [comment]
@JanFan there is a layer option `show_cursor_error` in checkers layer, please use gitter for general usage question.

**Comment by SteveClement** [comment]
> @JanFan there is a layer option `show_cursor_error` in checkers layer, please use gitter for general usage question.

Lol, yeah, more complicated questions do not get answers though...

**Comment by kfrncs** [comment]
`let g:spacevim_lint_on_save = 0` doesn't work for me. This thing is so annoying

**Comment by dmitvitalii** [comment]
> `let g:spacevim_lint_on_save = 0` doesn't work for me. This thing is so annoying

Adding `lint_on_save = false` to `[options]` in `~/.SpaceVim.d/init.toml` should help.

**Comment by oulrich1** [comment]
Try to set `g:spacevim_lint_on_save` to `0` under `.SpaceVim/autoload/SpaceVim.vim` directly.

I did try setting some settings for the checkers or even disable checkers layer, but none of that work. Another thing that worked was disabling `neomake` in the SpaceVim.d/init.toml, which worked but thats way overkill imo.

I think in this case, just have to go into the vim config to set exactly what you are looking for.

**Comment by miickel** [comment]
I managed to set `g:spacevim_lint_on_save` using [bootstrap#before](https://spacevim.org/documentation/#bootstrap-functions). Works fine!

**Comment by skullbyteshakya** [comment]
`$ vim ~/.SpaceVim/autoload/SpaceVim.vim`
and change `let g:spacevim_lint_on_save` from 1 to 0  

![image](https://user-images.githubusercontent.com/50847196/98401306-775c1b00-208b-11eb-88a4-3ca2822984a5.png)

**Comment by ziraqyoung** [comment]
This wont show errors if you have any.
I guess [this Reddit answer](https://www.reddit.com/r/SpaceVim/comments/abj58g/how_to_disable_error_checker_spacevim/) is the way to go, if you want errors to be signalled
Basically use `ale` instead of `neomake` which is the default. Add this in `init.toml` under `[options]`
```
[options]
  enable_neomake = false
  enable_ale     = true
```

**Comment by Herschenglime** [comment]
Is there a way to disable this pop up for a certain filetype? Currently I'm working on a long, journal-like document in latex using the lang#latex layer, and no matter what I do I can't disable it. I've put entries to disable lint on save in init.toml, my bootstrap file, and a file called tex_maps.vim that gets sourced by a FileType autocommand when I open a .tex file. 

When doing `:echo g:spacevim_lint_on_save` inside the document, it returns 0 yet every time I write the buffer the window appears. 

I'd rather not disable checking entirely, but it's super annoying for latex since the compiler already points out errors when compiling and the lacheck checker keeps yelling that my `\begin{document}` and `\end{document}` are unmatched despite both being present; the document compiles without issues. Since I need to save each time I want to update the processed pdf, this is even more irksome.

Additionally, is there a way to disable the neoplete snippets popup by default and toggle it on when needed? Since I'm primarily writing English words, all of the suggestions are distracting and irrelevant. However, when calling sections and whatnot, I'd still like to be able to use the autocomplete functionality. I was able to noremap a key sequence to toggle it on and off and that works, but it  still ends up enabled when I open my document which is annoying.

Thank you for your help! I really want to stick with SpaceVim since it's such a cool project and I've already sunk a good amount of time into learning it's specific configuration format.

**Comment by Herschenglime** [comment]
Adding `NeomakeDisable` on its own line in my latex-specific file called by `autocmd FileType tex source ~/path/to/file.vim` prevents it from popping up on save. It can still be run with `:Neomake` so this works great. Also, by adding `call deoplete#disable()` in the same file, it will be disabled on opening a latex file and can be toggled on as needed with `call deoplete#toggle()`, which can easily be mapped to a keyboard shortcut. 

I'm still not sure what was going on with the `g:spacevim_lint_on_save' option, but this works for me. Thanks!

**Comment by wsdjeg** [comment]
Move to google mail list.

**Comment by wsdjeg** [comment]
This issue has been fixed, the `checkers` layer can be disabled.
