### ISSUE TITLE
Windows: E121: Undefined variable: g:_spacevim_if_lua

### ISSUE THREAD

**Issue by ethamitc** [wsdjeg/SpaceVim#4082]
## Expected behavior, english is required
Expected SpaceVim to load without issue.

## The reproduce ways from Vim starting (Required!)
1. Download windows install script & run with administrator
2. Add `:source ~/.spacevim/init.vim` to .vimrc to fix spacevim not loading at all ([Mentioned Here](https://github.com/SpaceVim/SpaceVim/issues/3250#issuecomment-758182611))
3. Open vim and you will get the error `E121: Undefined variable: g:_spacevim_if_lua`
4. 
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
Not applicable

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

![image](https://user-images.githubusercontent.com/27776796/107668601-d919bb80-6c5e-11eb-8451-46e9da898d26.png)

**Comment by HDCharles** [comment]
The developer actually already handled this issue: https://github.com/SpaceVim/SpaceVim/issues/3928

by completely ignoring it

Given this response to basic functionality being broken, I'm going to assume this is something better avoided unless you are on Linux or enjoy fixing bugs

**Comment by wsdjeg** [comment]
you should following the installation guide. when using vim. you should load vimrc instead of init.vim. this valuable is definded in vimrc.

**Comment by HDCharles** [comment]
From what I can tell, that error message shows up if you don't have the DejaVu fonts installed that spacevim uses (you can get them [here](https://github.com/powerline/fonts/tree/master/DejaVuSansMono)). This is mentioned [here](https://github.com/Gabirel/Hack-SpaceVim/blob/master/en_US/installation/installation-for-windows.adoc#install-prerequisites) although the link is broken.

If this is fixed, you should be able to remove ':source ~/.spacevim/init.vim' from your vimrc without issue. I think the command mostly serves as a way to force spacevim to run and show an error message instead of silently failing.

**Comment by wsdjeg** [comment]
This issuse is opened for `E121: Undefined variable: g:_spacevim_if_lua`, and this value is definded in `vimrc` file, not `init.vim` file.
