### ISSUE TITLE
Failed to generate helptags for SpaceVim

### ISSUE THREAD

**Issue by typeoneerror** [wsdjeg/SpaceVim#4293]
I found this thread on gitter from last year indicating this has been fixed:

https://gitter.im/SpaceVim/SpaceVim?at=5fdf5829c746c6431cc6dfa5

But it's showing up when I start vim today. I ran `:SPUpdate`.

**Comment by wsdjeg** [comment]
what is the error message?

**Comment by typeoneerror** [comment]
@wsdjeg In the title of the issue, screenshot below

<img width="1032" alt="Screen Shot 2021-06-22 at 14 43 44" src="https://user-images.githubusercontent.com/218700/123003620-4dc8d900-d368-11eb-8f71-c83c79817387.png">

**Comment by wsdjeg** [comment]
run `git -C ~/.SpaceVim reset --hard origin/master  && git -C ~/.SpaceVim pull` in your terminal.

**Comment by typeoneerror** [comment]
@wsdjeg 

No luck, unfortunately. It's not a blocking bug, but it can stay open in case someone else figures out a fix.

```
[Edea] ~ $ git -C ~/.SpaceVim reset --hard origin/master && git -C ~/.SpaceVim pull
HEAD is now at c7eb99d6 Add wrap_line option (#4291)
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), 31.65 KiB | 368.00 KiB/s, done.
From https://github.com/SpaceVim/SpaceVim
   c7eb99d6..cad43708  master     -> origin/master
Updating c7eb99d6..cad43708
Fast-forward
 docs/documentation.md | 10 ++++++++++
 1 file changed, 10 insertions(+)
[Edea] ~ $ vim
[ SpaceVim ] [10:19:58] [ Warn ] Failed to generate helptags for SpaceVim
Press ENTER or type command to continue
[Edea] ~ $
```

**Comment by rene-descartes2021** [comment]
I encountered this error while adjusting the [Firejail vim.profile](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/vim.profile) for SpaceVim:
`[ SpaceVim ] [14:50:46] [ Warn ] Failed to generate helptags for SpaceVim`

So I ran the command manually `:helptags ~/dev/SpaceVim/doc` (I chose to put SpaceVim in ~/dev/SpaceVim not ~/.SpaceVim) and saw a more verbose error message:
`E152: Cannot open /home/browser/dev/SpaceVim/doc/tags for writing`
Maybe you will see the same or different error after running the command manually @typeoneerror.

In my case I can easily grant write access to the folder in Firejail's vim.profile. But I observe maybe it would be better to somehow do this async in order to improve SpaceVim startup time, or better would be to avoid file-system writing when not necessary, maybe only on install/upgrade?

I chose to just comment [the code](https://github.com/SpaceVim/SpaceVim/blob/c7eb99d6bb405a81f4eeba835b2b653010a2dcec/autoload/SpaceVim.vim#L1361-L1366) out for now.

**Comment by typeoneerror** [comment]
>  Maybe you will see the same or different error after running the command manually @typeoneerror.

I did

```
E670: Mix of help file encodings within a language: /Users/typeoneerror/.SpaceVim//bundle/vim-bepo/doc/bépo.txt
```

**Comment by wsdjeg** [comment]
If you want to run `:help spacevim` in vim, you need to generate tags for spacevim help file. and this can not be done when install spacevim, becaseu spacevim is installed via `git` comand, can we do not run `vim` command. so make sure you have write access to the root directory of spacevim.
