### ISSUE TITLE
docker keeping the plugins

### ISSUE THREAD

**Issue by vuvgaG** [wsdjeg/SpaceVim#4330]
docker run -it -v ~/.SpaceVim.d:/home/spacevim/.SpaceVim.d --rm spacevim/spacevim nvim

After doing this how can I keep the plugins. Once you close vim the container stops. When I re run the command it just installs the plugins again.

**Comment by wsdjeg** [comment]
try this

```
docker run -it -v ~/.cache/vimfiles:~/.SpaceVim.d:/home/spacevim/.SpaceVim.d --rm spacevim/spacevim nvim
```

**Comment by meicale** [comment]
> docker run -it -v ~/.SpaceVim.d:/home/spacevim/.SpaceVim.d --rm spacevim/spacevim nvim
> 
> After doing this how can I keep the plugins. Once you close vim the container stops. When I re run the command it just installs the plugins again.

You can try "docker commit " command and save a new image. Later, create you container based on this image. 
 
My question is how can I get all the plugin in the container? Because the plugin manager lazy load these plugins, I just want all of them install and can be used later even without access to the Internet.

**Comment by wsdjeg** [comment]
I can not reproduce this issue
