### ISSUE TITLE
E5108: Error executing lua ...pli/.SpaceVim/bundle/nvim-cmp/lua/cmp/config/default.lua:84: snippet engine is not configured.

### ISSUE THREAD

**Issue by ypli0629** [wsdjeg/SpaceVim#4637]
## The reproduce ways from Vim starting (Required!)
[[options]]    
  autocomplete_method = "nvim-cmp"
## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
hmm, I do not use `nvim-cmp`, this plugin should work out of box, in spacevim, if the autocomplete_method is nvim-cmp, we have added it into bundle dir, but I do not know why it can not be loaded without any config.

**Comment by comicchang** [comment]
Hi @wsdjeg,

I have reviewed your commit https://github.com/SpaceVim/SpaceVim/commit/207aa46f1db11d30890a070a2c1c11988245db09, and it seems like you were attempting to update the bundled nvim-cmp to version 3192a0c57837c1ec5bf298e4f3ec984c7d2d60c0. However, I have noticed that some files are missing, specifically the entire lua/cmp/view folder.
This might be because your .gitignore file contains a "view/" entry, which could have caused the files to be missing in the first place.

Could you please address this issue and fix the missing files? Additionally, I would appreciate it if you could update the nvim-cmp version as I believe it would be beneficial for the project.

Thank you for your attention to this matter.

**Comment by wsdjeg** [comment]
fixed. we will update nvim-cmp later.
