### ISSUE TITLE
Getting error: Unable to create directory "/home/sonul/.cache/SpaceVim/swap" for swap file, recovery impossible: permission denied

### ISSUE THREAD

**Issue by sonulohani** [wsdjeg/SpaceVim#4714]
![image](https://user-images.githubusercontent.com/2958681/193182396-96ef4ab8-a0e0-4276-8a79-688b3ad3c65a.png)

**Comment by jscd** [comment]
No idea why the cache dir is being made with the wrong permissions, but you can fix by adding read, write, and execute perms.
```sh
chmod -R u+rwx ~/.cache/SpaceVim
```

**Comment by wsdjeg** [comment]
The directory is made by https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/default.vim#L88-L102

**Comment by ElonSatoshi** [comment]
> No idea why the cache dir is being made with the wrong permissions, but you can fix by adding read, write, and execute perms.
> 
> ```shell
> chmod -R u+rwx ~/.cache/SpaceVim
> ```

Are the execute perms necessary?

> The directory is made by https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/default.vim#L88-L102

That's weird, I see 0700 on those, shouldn't that give the directory user read write and execute? 

This is what I'm getting when I install spacevim:

```
> ll -d ~/.cache/SpaceVim                                                                              23:53:31
d-w-r-xr-T 1 user user 0 Sep 30 23:53 /home/user/.cache/SpaceVim/
```



> No idea why the cache dir is being made with the wrong permissions, but you can fix by adding read, write, and execute perms.
> 
> ```shell
> chmod -R u+rwx ~/.cache/SpaceVim
> ```

I had to run this once, open and exit nvim, and run this once more in order for it to work.

**Comment by ElonSatoshi** [comment]
> The directory is made by https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/default.vim#L88-L102

That's weird, shouldn't that give the directory user read write and execute? 

This is what I'm getting when I install spacevim:

```
> ll -d ~/.cache/SpaceVim                                                                              23:53:31
d-w-r-xr-T 1 user user 0 Sep 30 23:53 /home/user/.cache/SpaceVim/
```

**Comment by the-moisrex** [comment]
From what I've gathered, in case of deleting `.cache/SpaceVim` directory, which may happen using cache cleanup utilities like [bleachbit](https://github.com/bleachbit/bleachbit), the problem only occurs when you first start with `nvim`.

But for the first time after deletion, if you start `vim` once, then both vim and nvim will work fine after that.

Running nvim for the first time would create the SpaceVim directory with the wrong permissions:

```
d-w-r-xr-T  2 user user 4.0K Oct  5 12:44 .
```

If you start with vim, then these are the permissions:
```
drwx------  4 user user 4.0K Oct  5 13:03 .
drwx------ 49 user user  12K Oct  5 13:03 ..
drwxr-xr-x  2 user user 4.0K Oct  5 13:03 conf
drwx------  6 user user 4.0K Oct  5 13:03 old
-rw-r--r--  1 user user   98 Oct  5 13:03 projects.json
```

Which is normal, but then if you run nvim after that, you'd get:

```
drwx------  7 user user 4.0K Oct  5 12:54 .
drwx------ 49 user user  12K Oct  5 12:54 ..
d-w-r-xr-T  2 user user 4.0K Oct  5 12:54 backup
drwxr-xr-x  2 user user 4.0K Oct  5 12:54 conf
drwx------  6 user user 4.0K Oct  5 12:54 old
-rw-r--r--  1 user user  208 Oct  5 12:54 projects.json
d-w-r-xr-T  2 user user 4.0K Oct  5 12:54 swap
d-w-r-xr-T  2 user user 4.0K Oct  5 12:54 undofile
```

The **Sticky** bit in the permissions get set and the whole thing is wrong again.

The two places that create these directories are:

https://github.com/SpaceVim/SpaceVim/blob/a559f215eb703c1cfa222dfc7fe363efc9f0af3f/lua/spacevim/default.lua#L93

https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/default.vim#L88-L102



The problem is in lua, `0700` is `700`. thus you'd be calling this in vim/nivm:
```vim
:silent call mkdir("not/gonna/work", 'p', 700)
```

while you should be calling this:
```vim
:silent call mkdir("not/gonna/work", 'p', 0700)
```
