### ISSUE TITLE
Add LaTeX tag support

### ISSUE THREAD

**Issue by Ionizing** [wsdjeg/SpaceVim#61]
- Add LaTeX syntax support.

**Comment by wsdjeg** [comment]
@IonizingRadiation @lervag

I want add latex support in SpaceVim, I just search in google, and I found there are two project https://github.com/lervag/vimtex and https://github.com/vim-latex/vim-latex, I do not use latex, I can not find the differences of these two project, which one should I add into SpaceVim.

**Comment by lervag** [comment]
I don't really want to have an opinion on what should be part of SpaceVim. I personally will never encourage anyone to use SpaceVim, since I think people should build their own setup from scratch.

However, I would still claim that vimtex is a more modern and (IMHO) better approach to a LaTeX plugin for vim than vim-latex.

**Comment by wsdjeg** [comment]
@lervag Thanks, I will use vimtex, 
BTW, I use vim for more than 5 years , I know what you thinking. But SpaceVim by defult maybe has no plugins in the feature, but it provide different plugin groups, user do not have to search for the plugins he want. that is the main goal of SpaceVim. it is not just same thing as a traditional vim distribution.

**Comment by wsdjeg** [comment]
vimtex is added now.

**Comment by lervag** [comment]
@wsdjeg Ok, thanks for the input, and good luck on the venture!

**Comment by Ionizing** [comment]
@wsdjeg Thank you for your job. TeXers will be grateful.

**Comment by wsdjeg** [comment]
welcome.
