### ISSUE TITLE
Byobu-Tmux crash 'lost-server' when launch neovim with SapceVim

### ISSUE THREAD

**Issue by hieudang9** [wsdjeg/SpaceVim#750]
## Expected behavior, english is recommended
**Byobu-Tmux crash `lost-server` when launch neovim with SapceVim**

## Environment Information
- OS: `Centos 7`
- vim version: `7.4.1`
- neovim version: `0.2`

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
what is the reproduce step, and what is the error message,

**Comment by csghone** [comment]
I faced the same problem.
Seems to be problem with byobu 5.7  + tmux 1.8 combo.
It went away when I migrated to latest version from `sudo add-apt-repository ppa:byobu/ppa`

**Comment by wsdjeg** [comment]
@csghone Thanks, but I never use byobu and tmux, I do not know why the old version of byobu will cause this problem.

**Comment by csghone** [comment]
@wsdjeg There are several issues with vim + tmux or vim + gnome/mate-terminal - mostly related some older libvte versions. This could possibly be something like that.

**Comment by wsdjeg** [comment]
Can you have a try with termite?

**Comment by dbrw** [comment]
I have this issue too.

I believe it is related to neovim & tmux rather than spacevim & tmux. I tested using nvim (without spacevim) on tmux and got `[lost server]` error.

tmux version `2.7`
nvim version `v0.2.2`  with compilation `/usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser`

Maybe opening issue on nvim and referencing this issue there would be better.

**Comment by wsdjeg** [comment]
ok Thanks

**Comment by diego898** [comment]
@wsdjeg did you ever get this fixed? Im having the same problem with just neovim and byobu/tmux

**Comment by lyerox** [comment]
@wsdieg did you ever get this fixed? I'm having the same problem with spacevim(neovim backend) and byobu/tmux on CentOS 7

**Comment by stara-garn** [comment]
Issue is still present for :
```
- Centos7
- tmux 1.8
- byobu version 5.92
- NVIM v0.3.0
```

but it works after commented the line:
`#set -g terminal-overrides 'xterm*:smcup@:rmcup@'`
in the file `/usr/share/byobu/profiles/tmux`

I hope it can help
