### ISSUE TITLE
设置了for power line字体，还是出现了问号乱码

### ISSUE THREAD

**Issue by gradyjiang** [wsdjeg/SpaceVim#771]
## Expected behavior, english is recommended
设置了for power line字体，大部分乱码都解决了，但左上角还是出现了问号乱码，其次觉得箭头有些偏小，不知道上啥原因，麻烦帮忙分析一下，谢谢

## Environment Information
- OS: MacOS 10.12.6 
- vim version: VIM - Vi IMproved 8.0
- neovim version: None

## The reproduce ways from Vim starting (Required!)
Homebrew

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
<img width="1001" alt="4d4b4760-baa3-476c-a26c-b661c3a5488c" src="https://user-images.githubusercontent.com/30748169/29124569-ddc39274-7d4b-11e7-9cfe-48f27eae8c3b.png">

**Comment by icearith** [comment]
1. The question mark on the top left corner is an ICON for file. Check [Nerd font](https://github.com/ryanoasis/nerd-fonts). You could download a patched font or patch a your own file, it's up to you. 

2. Alignment: this issue is often related to ASCII font and NON-ASCII font setting. Some of the font shows a pretty good performance. A pic is as follows: 

![screen shot 2017-08-09 at 4 20 55 pm](https://user-images.githubusercontent.com/2555093/29129457-be6b38a0-7d1e-11e7-9f6e-9bf5c0a44a59.png)

Font configuration is also provided:

![screen shot 2017-08-09 at 4 21 34 pm](https://user-images.githubusercontent.com/2555093/29129478-d8004db4-7d1e-11e7-97ed-3d5ea9bf3558.png)

**Comment by gradyjiang** [comment]
@icearith thank you , your tips is very effective

**Comment by milkdeliver** [comment]
Homebrew Fonts on macOS (OS X)
```
brew tap caskroom/fonts
brew cask install font-hack-nerd-font
```

**Comment by lixplor** [comment]
I met same problems. Thanks to @icearith  @milkdeliver 
Below is the way to solve it

1. install nerd font with homebrew:

```bash
brew tap caskroom/fonts
brew cask install font-hack-nerd-font
```

2. Change font setting in your terminal preference (e.g. iTerm2):
choose `Hack Nerd Font`
![Imgur](https://i.imgur.com/QEpbnqc.png)

3. Restart vim

**Comment by wsdjeg** [comment]
a nice guide for set fonts.

**Comment by Peresh** [comment]
<img alt="4d4b4760-baa3-476c-a26c-b661c3a5488c" width="1001" src="https://user-images.githubusercontent.com/30748169/29124569-ddc39274-7d4b-11e7-9cfe-48f27eae8c3b.png">

好看呐，这是啥主题？

**Comment by finalxcode** [comment]
thanks
