### ISSUE TITLE
Talking about SpaceVim plugin groups.

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#9]
As you can see, in SpaceVim if all the plugin is loaded, it is 200+ plugin, now my main work is split them into different groups, and then the user can just load the groups he want. other plugins will not be loaded. but hou should I split them?
just same as spacemacs? and as I can see, in spacemacs all layers is here https://github.com/syl20bnr/spacemacs/tree/master/layers.

**Comment by fno2010** [comment]
When we talk about the **plugin groups**, may I have a quick question? What is the limitation of the **Layer** design in vim? If no limitation, why not just use this design to implement modular configuration? If we can find some limitation, that should be great. Because we can propose some novel things. And it can be the killer function of SpaceVim.

@wsdjeg how do you think about it?

**Comment by wsdjeg** [comment]
@fno2010 I am not sure you will support SpaceVim, as I can see you are staring and using space-vim, but as a discussion, here is the limitation of layer design like space-vim.
1. as a plugin author, I prefer autoload func such as `SpaceVim#Foo()`, this func will only be used by SpaceVim, in space-vim, most func are global func without name space such as `UserInit()`, It is bad design, these func maybe override by other plugins.
2. vim has autoload feature, it is name space friendly, we should use these feature instead of use `:source` command.
3. I use dein as plugin manager, it support more options than vim-plug. it help SpaceVim to manager both plugins and plugin-configs.
3. I use plugin groups, and put plugins in a single file, I think no need split them into different file, just use a dictionary. loading one file  will be faster than finding and loading multiple files。
4. language specific plugin should be lazy load on filetype. so maybe all of them should be in group `lang`, for example we load plugin for java by use `lang/java` group.
here is what I think. 

hi @Shougo @mhinz what do you think of this?

at the end I want to say we need support, no only vim/viml user, but all language developper, maybe they can help me with the lang specific plugin.

**Comment by fno2010** [comment]
Cool! Thanks for your reply, @wsdjeg. We need to push this discussion because I think it is very crucial for this project.

I will not really use both SpaceVim and space-vim now, because I know both are still not stable. I go to contribute for space-vim because its design is clear. This project misses some major documents so that I cannot learn about its main idea and philosophy.

Let me give some quick comments:

I will skip `1-3` because it is not crucial in the current stage. I agree that autoload is better. But fixing this issue is not hard. At least it is very clear.

I think `4` is your main idea. But spliting or not is also not crucial. The idea of spacemacs is to manage the usage of different plugins by defining some formalized packages (we can call them "layers", "plugin groups" or whatever). And each formalized package need to define following things: used plugins, default configs, simple options, keybindings and the usage/document. The definition of everything will be formalized by the framework. So what's your real main idea?

For `5`, I agree that `lazy load` is necessary. But if the usage of the platform is not clear, who can develop more extensions for this platform?

So my suggestion is to freeze an inital working framework and document the design and usage.

**Comment by wsdjeg** [comment]
I think I should update the document about SpaceVim. org mode is nice, will try to use it.

**Comment by yqrashawn** [comment]
Agreed. Document need to be up to date. User need list of groups. A configuration file with some default config and document is greate. So that user can at least have a try.

**Comment by wsdjeg** [comment]
@fno2010 I will release 0.1.0, and I think the main layers has been finished. would you like to have a try?
