### ISSUE TITLE
the command is not available in this version: python3 << endpython

### ISSUE THREAD

**Issue by ratelgogo** [wsdjeg/SpaceVim#955]
- OS: macOS HS 10.13
- vim version: 8.0
- neovim version: 0.2.0

![image](https://user-images.githubusercontent.com/23555154/32218858-4081f372-be67-11e7-9375-99678e449d4c.png)
neovim is fine

**Comment by bric3** [comment]
On a brand new install, no .cache, no .SpaceVim*.

- OS: Mac OSX 10.13.0
- vim version: VIM - Vi IMproved 8.0.642
- neovim version: NVIM v0.2.0
- SpaceVim version: 0.5.0-dev (commit 82461040e32f3ef8e4c7f0ffa209d944d1f1b61d)
- `python --version`: Python 2.7.10
- `python3 --version`: Python 3.6.3

On my side neovim is not fine, and vim fails with the same error : 

```
➜ nvim
Error detected while processing function rtags#InitPython:
line    9:
E117: Unknown function: provider#python3#Call
Press ENTER or type command to continue
```

-----

It seems related to https://github.com/SpaceVim/SpaceVim/issues/940

Indeed passing the command `:version` I see in the features included section `-python3`. Also it seems it is the high sierra vim version `/usr/bin/vim`. Installing vim from homebrew did not change a thing because vim is not compiled with python3 support.

**Comment by ratelgogo** [comment]
@bric3 try pip3 install --user neovim

**Comment by ratelgogo** [comment]
my vim do not support python3....

**Comment by bric3** [comment]
But then why is it trying to execute python3, I have python 2 as well.

**Comment by bric3** [comment]
@ratelgogo But then why is it trying to execute `python3`, I have `python` 2 as well.

**Comment by ratelgogo** [comment]
I don’t know 
发自网易邮箱大师
On 11/06/2017 20:33, Brice Dutheil wrote: @ratelgogo But then why is it trying to execute python3, I have python 2 as well.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SpaceVim/SpaceVim","title":"SpaceVim/SpaceVim","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SpaceVim/SpaceVim"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bric3 in #955: @ratelgogo But then why is it trying to execute `python3`, I have `python` 2 as well."}],"action":{"name":"View Issue","url":"https://github.com/SpaceVim/SpaceVim/issues/955#issuecomment-342135472"}}}

**Comment by bric3** [comment]
I still don't know about why python3 is executed, while my default vim install is not compiled with python 3 support. Even with tricks like `let g:pymode_python = 'python'` it still try to use `python3`. But in the end I was able to fix this by _forcing_ python 3 in to vim (by reinstalling it, on OSX `brew reinstall vim --with-python3`)

-----------------------------------------------------------------

Regarding neovim, I found this useful issue neovim/neovim#3577, and the error may happen because something totally different than python stuff. On of the commenter advises to type `:CheckHealth` to see the real problem, indeed it seems to be the ruby provider that causes trouble.

```
## Python 2 provider (optional)
  - INFO: Disabled. g:loaded_python_provider=1

## Python 3 provider (optional)
  - INFO: Disabled. g:loaded_python3_provider=1

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
  - WARNING: Missing "neovim" gem.
    - SUGGESTIONS:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".
```

Fixed by installing the providers

```
gem install neovim
pip2 install --upgrade neovim
pip3 install --upgrade neovim
```

More information on neovim providers [here](https://neovim.io/doc/user/provider.html).

---------------------------------------------------------------------------------

For both **vim** and **neovim** I had to enable **python 3**.
